apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-berd
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    name: {{ .Release.Name }}-ui