apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-config
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-berd
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: Helm
data:
  REACT_APP_API_URL: {{ .Values.ui.apiURL }}