apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-ui
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: ts-berd
        app.kubernetes.io/component: ui
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: ui
        image: {{ .Values.images.ui }}
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
            cpu: 100m
        ports:
          - containerPort: 80
        env:
          - name: REACT_APP_API_URL
            value: {{ .Values.ui.apiURL }}
          - name: TARGET_LINK
            value: {{ .Values.ingress.dns }}
      imagePullSecrets:
        - name: regcred