apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend }}
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 100Mi
        ports:
          - containerPort: 80
        env:
          - name: REACT_APP_API_URL
            value: {{ .Values.frontend.apiURL }}
          - name: TARGET_LINK
            value: {{ .Values.ingress.dns }}