apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gw
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-health
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    name: {{ .Release.Name }}-gw