apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ols4-csh-gateway
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-ols4-csh-gateway
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-ols4-csh-gateway
        project: nfdi4health
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: nfdi4health-gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: ols4-csh-gateway
        image: {{ .Values.images.ui }}
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
            cpu: 100m
      imagePullSecrets:
        - name: regcred
